block( 'tour' ).elem( 'place' ).content()( () => {
  return {
    block: 'fieldset',
    legend: 'Выбор мест',
    content: {
      block: 'form-field',
      mods: {
        type: 'checkbox-group',
      },
      id: 'place',
      name: 'place',
      content: [
        {
          block: 'checkbox-group',
          mods: { type: 'button' },
          val: [ 22, 36, 50 ],
          options: [
            { val: 1, text: 1 },
            { val: 2, text: 2 },
            { val: 3, text: 3 },
            { val: 4, text: 4 },
            { val: 5, text: 5 },
            { val: 6, text: 6 },
            { val: 7, text: 7 },
            { val: 8, text: 8 },
            { val: 9, text: 9 },
            { val: 10, text: 10 },
            { val: 11, text: 11 },
            { val: 12, text: 12 },
            { val: 13, text: 13 },
            { val: 14, text: 14 },
            { val: 15, text: 15 },
            { val: 16, text: 16 },
            { val: 17, text: 17 },
            { val: 18, text: 18 },
            { val: 19, text: 19 },
            { val: 20, text: 20 },
            { val: 21, text: 21 },
            { val: 22, text: 22 },
            { val: 23, text: 23 },
            { val: 24, text: 24 },
            { val: 25, text: 25 },
            { val: 26, text: 26 },
            { val: 27, text: 27 },
            { val: 28, text: 28 },
            { val: 29, text: 29 },
            { val: 30, text: 30 },
            { val: 31, text: 31 },
            { val: 32, text: 32 },
            { val: 33, text: 33 },
            { val: 34, text: 34 },
            { val: 35, text: 35 },
            { val: 36, text: 36 },
            { val: 37, text: 37 },
            { val: 38, text: 38 },
            { val: 39, text: 39 },
            { val: 40, text: 40 },
            { val: 41, text: 41 },
            { val: 42, text: 42 },
            { val: 43, text: 43 },
            { val: 44, text: 44 },
            { val: 45, text: 45 },
            { val: 46, text: 46 },
            { val: 47, text: 47 },
            { val: 48, text: 48 },
            { val: 49, text: 49 },
            { val: 50, text: 50 },
            { val: 51, text: 51 },
            { val: 52, text: 52 },
            { val: 53, text: 53 },
            { val: 54, text: 54 },
            { val: 55, text: 55 },
          ]
        }
      ]
    }
  }
} );
